modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="chicken_roost"
version="0.2.4"
displayName="Roost Ultimate"
credits="Roost Ultimate"
displayURL="https://tarantel.yt"
updateJSONURL="https://raw.githubusercontent.com/TarantelTM/Roost/main/1.18.5_update.JSON"
logoFile="logo.png"
authors="Tarantel, timrwood, codewarrior0"

[[dependencies.chicken_roost]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




